
version: "3.9"

services:
  web:
    image: node:20-alpine
    container_name: lovable_react_web
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      # Randomized high port to host; Vite's default port is 5173
      - "32857:5173"
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=5173
    command: sh -c "npm install && npm run dev"
