// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://soonsgomaxnbturfhwea.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvb25zZ29tYXhuYnR1cmZod2VhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTI2MTUsImV4cCI6MjA2NTQ2ODYxNX0.RWS6aWyYK07K0baZwRaYWMhtonmsTsztPE6I1MxvMUo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);